version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mi_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: dobleq3
      MONGO_INITDB_DATABASE: mi_basedatos
    volumes:
      - ./mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
